### ISSUE TITLE
mandel.bf output is incorrect

### ISSUE THREAD

**Issue by adrianton3** [serprex/Befunge#3]
https://github.com/catseye/Befunge-93/blob/master/eg/mandel.bf

There are some extra `#` symbols in a grid-like pattern in the output; they shouldn't be there

**Comment by serprex** [comment]
Using which interpreter?

**Comment by adrianton3** [comment]
I found it funny that you reported https://github.com/adrianton3/befunjit/issues/8 and at the time I used your interpreter to check what the correct output would look like and that's when I submitted back your bug 😄 

I'm happy that you're maintaining this - there should be more fast and correct implementations out there!

Side-note: do you have any plans on creating a benchmark suite? Several bf programs that you think are very well (or not so well) optimized by your implementation
